# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('header', models.TextField()),
                ('record', models.TextField()),
            ],
        ),
    ]
