# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 04:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170401_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 1, 4, 9, 52, 984992)),
            preserve_default=False,
        ),
    ]
